Add version-check script (#118)

diff --git a/.github/workflows/onpullrequest.yml b/.github/workflows/onpullrequest.yml
--- a/.github/workflows/onpullrequest.yml
+++ b/.github/workflows/onpullrequest.yml
@@ -4,8 +4,24 @@ on:
   pull_request:
 
 jobs:
-  build-test:
+ version-check:
     runs-on: [ self-hosted ]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      
+      - name: version-check
+        run: |
+          /bin/bash version-check.sh
+          if [[ $? -eq 1 ]]; then
+            echo "version check failed"
+            exit 1
+          fi
+          
+ build-test:
+    runs-on: [ self-hosted ]
+    needs: [ "version-check" ]
     env:
       http_proxy: ${{ secrets.HTTP_PROXY }}
       https_proxy: ${{ secrets.HTTPS_PROXY }}
@@ -38,7 +54,8 @@ jobs:
       - name: Build Installer
         run: make installer
 
-  cleanup-images-bins:
+
+ cleanup-images-bins:
     runs-on: [ self-hosted ]
     needs: [ "build-test" ]
     steps:
